<div class="container-fluid p-0">

  <div class="row g-0 flex-column flex-md-row">
    <div class="col col-12 col-md-4 d-md-block d-none">

      <img class="img-fluid d-md-block d-none" src="<?= $this->basePath('img/we-are-open.jpg') ?>" alt="Nous sommes ouverts">
    </div>

    <div class="col col-12 col-md-8 p-3">
      <div class="mt-3 mb-3 h1">
        Créez votre profil collaborateur
      </div>
      <form action="<?= $this->url('inscription'); ?>" method="POST">

        <div class="container-fluid p-0">

          <div class="row">

            <div class="col col-6">

              <div id="groupGenre" class="mb-3">

                <label class="form-label text-decoration-underline" for="inputGenre">
                  Genre
                </label>
                <select name="genre" id="inputGenre" class="form-control">
                  <option value="monsieur" <?= ($this->collaborateur['genre'] == 'monsieur') ? 'selected' : '' ?>>
                    Monsieur
                  </option>
                  <option value="madame" <?= ($this->collaborateur['genre'] == 'madame') ? 'selected' : '' ?>>
                    Madame
                  </option>
                  <option value="sansreponse" <?= ($this->collaborateur['genre'] == 'sansreponse') ? 'selected' : '' ?>>
                    Ne pas répondre
                  </option>
                </select>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col col-12 col-md-6">

              <div class="mb-3">

                <label class="form-label" for="inputNom">
                  Nom
                </label>
                <input type="text" name="nom" value="<?= $this->collaborateur['nom'] ?? ''; ?>" class="form-control" id="inputNom">
              </div>
            </div>

            <div class="col col-12 col-md-6">

              <div class="mb-3">

                <label class="form-label" for="inputPrenom">
                  Prénom
                </label>
                <input type="text" name="prenom" value="<?= $this->collaborateur['prenom'] ?? ''; ?>" class="form-control" id="inputPrenom">
              </div>
            </div>
          </div>
        </div>

        <div class="row">

          <div class="col col-6">

            <div class="mb-3">

              <label class="form-label" for="inputDateNaissance">
                Date de naissance
              </label>
              <input type="date" name="date_naissance" value="<?= $this->collaborateur['date_naissance'] ?? ''; ?>" class="form-control" id="inputDateNaissance">
            </div>
          </div>
        </div>

        <div class="row">

          <div class="col col-12">

            <div class="mb-5">
              <button type="submit" class="btn btn-secondary shadow shadow-lg">
                Enregistrer
              </button>
            </div>

          </div>
        </div>
      </form>
    </div>
  </div>
</div>