<?php
/**
 * @var $this
 */


?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="<?= $this->basePath('css/styles.css') ?>" rel="stylesheet">

    <?= $this->siteTitle() ?>
</head>
<body>
    <main>
        <header class="container-fluid px-4 py-2 bg-dark text-light">
            <nav class="navbar navbar-dark bg-transparent">
                <a href="<?= $this->basePath('/') ?>" class="navbar-brand">
                    <?= $this->siteTitle()->renderTitle(); ?>
                </a>

                <nav class="nav">
                    <a class="nav-link link-light bg-primary rounded rounded-pill" href="#">S'inscrire</a>
                    <a class="nav-link link-light bg-secondary rounded rounded-pill" href="#">Se connecter</a>
                </nav>
            </nav>
        </header>

        <section class="container-fluid p-0">
            <?= $this->content ?>
        </section>

        <footer class="container-fluid px-4 py-2 bg-dark text-light">
            <div class="d-flex justify-content-end">
                <span>&COPY; <?= (new DateTime())->format('Y'); ?></span>
            </div>
        </footer>
    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>
