<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$featuresClasses = implode(' ', array(
    "px-4",
    "py-2",
	"mb-4",
	"me-sm-4",
	"text-white",
	"fw-bold",
	"shadow",
	"bg-secondary",
	"rounded",
	"rounded-pill"
));

?>
<div class="container-fluid p-0">
    <div class="row g-0 flex-column-reverse flex-md-row justify-content-end bg-primary text-light">
        <div class="col col-12 col-md-6 order-2 order-md-0">
            <div class="p-5 text-md-start text-end">
                <h1 class="display-4">Solution de gestion<br />des collaborateurs</h1>

                <p class="lead">
                    Félicitations! Vous avez démarré l'application avec succès.
                </p>

                <p>
                    Ce logiciel est une démonstration de la programmation orientée objet
                    avec le langage PHP.
                </p>

                <hr class="my-4">

                <nav class="d-flex flex-wrap justify-content-around justify-content-md-end">
                    <a class="btn btn-dark btn-lg mb-4 mx-4" href="https://github.com/jokebox90/demo-poo" target="_blank">
                        Suivez-nous sur GitHub &raquo;
                    </a>
                </nav>
            </div>
        </div>
        <div class="col col-12 col-md-6 order-2 order-md-1 bg-thirdly">
            <img class="img-fluid" src="<?= $this->basePath('img/office-people.jpg') ?>" alt="Réunion des ollaborateurs" />
        </div>
        <div class="col col-12 col-md-6 order-0 order-md-2 bg-thirdly text-dark p-3">
            <h3 class="text-decoration-underline text-center mb-3">
                Fonctionnalités
            </h3>

            <ul class="d-flex flex-row flex-wrap justify-content-center list-unstyled">
                <li class="<?= $featuresClasses; ?>">
                    Lister les collaborateurs
                </li>
                <li class="<?= $featuresClasses; ?>">
                    Ajouter un collaborateur
                </li>
                <li class="<?= $featuresClasses; ?>">
                    Editer un collaborateur
                </li>
                <li class="<?= $featuresClasses; ?>">
                    Supprimer un collaborateur
                </li>
                <li class="<?= $featuresClasses; ?>">
                    Augmenter tous les salaires
                </li>
                <li class="<?= $featuresClasses; ?>">
                    Rechercher par critères
                </li>
            </ul>
        </div>
    </div>
</div>
